// Code generated by protoc-gen-go. DO NOT EDIT.
// source: tcp_service.proto

package proto

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type UserInfoReq struct {
	UserId               string   `protobuf:"bytes,1,opt,name=UserId,proto3" json:"UserId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserInfoReq) Reset()         { *m = UserInfoReq{} }
func (m *UserInfoReq) String() string { return proto.CompactTextString(m) }
func (*UserInfoReq) ProtoMessage()    {}
func (*UserInfoReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_de15a12e8d808d3f, []int{0}
}

func (m *UserInfoReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserInfoReq.Unmarshal(m, b)
}
func (m *UserInfoReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserInfoReq.Marshal(b, m, deterministic)
}
func (m *UserInfoReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserInfoReq.Merge(m, src)
}
func (m *UserInfoReq) XXX_Size() int {
	return xxx_messageInfo_UserInfoReq.Size(m)
}
func (m *UserInfoReq) XXX_DiscardUnknown() {
	xxx_messageInfo_UserInfoReq.DiscardUnknown(m)
}

var xxx_messageInfo_UserInfoReq proto.InternalMessageInfo

func (m *UserInfoReq) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

type UserInfoRsp struct {
	UserId               string   `protobuf:"bytes,1,opt,name=UserId,proto3" json:"UserId,omitempty"`
	NickName             string   `protobuf:"bytes,2,opt,name=NickName,proto3" json:"NickName,omitempty"`
	ProfilePicture       string   `protobuf:"bytes,3,opt,name=ProfilePicture,proto3" json:"ProfilePicture,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserInfoRsp) Reset()         { *m = UserInfoRsp{} }
func (m *UserInfoRsp) String() string { return proto.CompactTextString(m) }
func (*UserInfoRsp) ProtoMessage()    {}
func (*UserInfoRsp) Descriptor() ([]byte, []int) {
	return fileDescriptor_de15a12e8d808d3f, []int{1}
}

func (m *UserInfoRsp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserInfoRsp.Unmarshal(m, b)
}
func (m *UserInfoRsp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserInfoRsp.Marshal(b, m, deterministic)
}
func (m *UserInfoRsp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserInfoRsp.Merge(m, src)
}
func (m *UserInfoRsp) XXX_Size() int {
	return xxx_messageInfo_UserInfoRsp.Size(m)
}
func (m *UserInfoRsp) XXX_DiscardUnknown() {
	xxx_messageInfo_UserInfoRsp.DiscardUnknown(m)
}

var xxx_messageInfo_UserInfoRsp proto.InternalMessageInfo

func (m *UserInfoRsp) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

func (m *UserInfoRsp) GetNickName() string {
	if m != nil {
		return m.NickName
	}
	return ""
}

func (m *UserInfoRsp) GetProfilePicture() string {
	if m != nil {
		return m.ProfilePicture
	}
	return ""
}

type UserLoginReq struct {
	UserId               string   `protobuf:"bytes,1,opt,name=UserId,proto3" json:"UserId,omitempty"`
	Password             string   `protobuf:"bytes,2,opt,name=Password,proto3" json:"Password,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserLoginReq) Reset()         { *m = UserLoginReq{} }
func (m *UserLoginReq) String() string { return proto.CompactTextString(m) }
func (*UserLoginReq) ProtoMessage()    {}
func (*UserLoginReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_de15a12e8d808d3f, []int{2}
}

func (m *UserLoginReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserLoginReq.Unmarshal(m, b)
}
func (m *UserLoginReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserLoginReq.Marshal(b, m, deterministic)
}
func (m *UserLoginReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserLoginReq.Merge(m, src)
}
func (m *UserLoginReq) XXX_Size() int {
	return xxx_messageInfo_UserLoginReq.Size(m)
}
func (m *UserLoginReq) XXX_DiscardUnknown() {
	xxx_messageInfo_UserLoginReq.DiscardUnknown(m)
}

var xxx_messageInfo_UserLoginReq proto.InternalMessageInfo

func (m *UserLoginReq) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

func (m *UserLoginReq) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

type UserLoginRsp struct {
	Status               bool     `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	Msg                  string   `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserLoginRsp) Reset()         { *m = UserLoginRsp{} }
func (m *UserLoginRsp) String() string { return proto.CompactTextString(m) }
func (*UserLoginRsp) ProtoMessage()    {}
func (*UserLoginRsp) Descriptor() ([]byte, []int) {
	return fileDescriptor_de15a12e8d808d3f, []int{3}
}

func (m *UserLoginRsp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserLoginRsp.Unmarshal(m, b)
}
func (m *UserLoginRsp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserLoginRsp.Marshal(b, m, deterministic)
}
func (m *UserLoginRsp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserLoginRsp.Merge(m, src)
}
func (m *UserLoginRsp) XXX_Size() int {
	return xxx_messageInfo_UserLoginRsp.Size(m)
}
func (m *UserLoginRsp) XXX_DiscardUnknown() {
	xxx_messageInfo_UserLoginRsp.DiscardUnknown(m)
}

var xxx_messageInfo_UserLoginRsp proto.InternalMessageInfo

func (m *UserLoginRsp) GetStatus() bool {
	if m != nil {
		return m.Status
	}
	return false
}

func (m *UserLoginRsp) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

type UserEditReq struct {
	UserId               string   `protobuf:"bytes,1,opt,name=UserId,proto3" json:"UserId,omitempty"`
	NewPassword          string   `protobuf:"bytes,2,opt,name=NewPassword,proto3" json:"NewPassword,omitempty"`
	OldPassword          string   `protobuf:"bytes,3,opt,name=OldPassword,proto3" json:"OldPassword,omitempty"`
	NickName             string   `protobuf:"bytes,4,opt,name=NickName,proto3" json:"NickName,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserEditReq) Reset()         { *m = UserEditReq{} }
func (m *UserEditReq) String() string { return proto.CompactTextString(m) }
func (*UserEditReq) ProtoMessage()    {}
func (*UserEditReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_de15a12e8d808d3f, []int{4}
}

func (m *UserEditReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserEditReq.Unmarshal(m, b)
}
func (m *UserEditReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserEditReq.Marshal(b, m, deterministic)
}
func (m *UserEditReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserEditReq.Merge(m, src)
}
func (m *UserEditReq) XXX_Size() int {
	return xxx_messageInfo_UserEditReq.Size(m)
}
func (m *UserEditReq) XXX_DiscardUnknown() {
	xxx_messageInfo_UserEditReq.DiscardUnknown(m)
}

var xxx_messageInfo_UserEditReq proto.InternalMessageInfo

func (m *UserEditReq) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

func (m *UserEditReq) GetNewPassword() string {
	if m != nil {
		return m.NewPassword
	}
	return ""
}

func (m *UserEditReq) GetOldPassword() string {
	if m != nil {
		return m.OldPassword
	}
	return ""
}

func (m *UserEditReq) GetNickName() string {
	if m != nil {
		return m.NickName
	}
	return ""
}

type UserEditRsp struct {
	Status               bool     `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	Msg                  string   `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserEditRsp) Reset()         { *m = UserEditRsp{} }
func (m *UserEditRsp) String() string { return proto.CompactTextString(m) }
func (*UserEditRsp) ProtoMessage()    {}
func (*UserEditRsp) Descriptor() ([]byte, []int) {
	return fileDescriptor_de15a12e8d808d3f, []int{5}
}

func (m *UserEditRsp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserEditRsp.Unmarshal(m, b)
}
func (m *UserEditRsp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserEditRsp.Marshal(b, m, deterministic)
}
func (m *UserEditRsp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserEditRsp.Merge(m, src)
}
func (m *UserEditRsp) XXX_Size() int {
	return xxx_messageInfo_UserEditRsp.Size(m)
}
func (m *UserEditRsp) XXX_DiscardUnknown() {
	xxx_messageInfo_UserEditRsp.DiscardUnknown(m)
}

var xxx_messageInfo_UserEditRsp proto.InternalMessageInfo

func (m *UserEditRsp) GetStatus() bool {
	if m != nil {
		return m.Status
	}
	return false
}

func (m *UserEditRsp) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

type UploadProfileReq struct {
	UserId               string   `protobuf:"bytes,1,opt,name=UserId,proto3" json:"UserId,omitempty"`
	Url                  string   `protobuf:"bytes,2,opt,name=Url,proto3" json:"Url,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UploadProfileReq) Reset()         { *m = UploadProfileReq{} }
func (m *UploadProfileReq) String() string { return proto.CompactTextString(m) }
func (*UploadProfileReq) ProtoMessage()    {}
func (*UploadProfileReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_de15a12e8d808d3f, []int{6}
}

func (m *UploadProfileReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UploadProfileReq.Unmarshal(m, b)
}
func (m *UploadProfileReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UploadProfileReq.Marshal(b, m, deterministic)
}
func (m *UploadProfileReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UploadProfileReq.Merge(m, src)
}
func (m *UploadProfileReq) XXX_Size() int {
	return xxx_messageInfo_UploadProfileReq.Size(m)
}
func (m *UploadProfileReq) XXX_DiscardUnknown() {
	xxx_messageInfo_UploadProfileReq.DiscardUnknown(m)
}

var xxx_messageInfo_UploadProfileReq proto.InternalMessageInfo

func (m *UploadProfileReq) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

func (m *UploadProfileReq) GetUrl() string {
	if m != nil {
		return m.Url
	}
	return ""
}

type UploadProfileRsp struct {
	Status               bool     `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	Msg                  string   `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UploadProfileRsp) Reset()         { *m = UploadProfileRsp{} }
func (m *UploadProfileRsp) String() string { return proto.CompactTextString(m) }
func (*UploadProfileRsp) ProtoMessage()    {}
func (*UploadProfileRsp) Descriptor() ([]byte, []int) {
	return fileDescriptor_de15a12e8d808d3f, []int{7}
}

func (m *UploadProfileRsp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UploadProfileRsp.Unmarshal(m, b)
}
func (m *UploadProfileRsp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UploadProfileRsp.Marshal(b, m, deterministic)
}
func (m *UploadProfileRsp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UploadProfileRsp.Merge(m, src)
}
func (m *UploadProfileRsp) XXX_Size() int {
	return xxx_messageInfo_UploadProfileRsp.Size(m)
}
func (m *UploadProfileRsp) XXX_DiscardUnknown() {
	xxx_messageInfo_UploadProfileRsp.DiscardUnknown(m)
}

var xxx_messageInfo_UploadProfileRsp proto.InternalMessageInfo

func (m *UploadProfileRsp) GetStatus() bool {
	if m != nil {
		return m.Status
	}
	return false
}

func (m *UploadProfileRsp) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

type RegisterUserReq struct {
	UserId               string   `protobuf:"bytes,1,opt,name=UserId,proto3" json:"UserId,omitempty"`
	Password             string   `protobuf:"bytes,2,opt,name=Password,proto3" json:"Password,omitempty"`
	NickName             string   `protobuf:"bytes,3,opt,name=NickName,proto3" json:"NickName,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RegisterUserReq) Reset()         { *m = RegisterUserReq{} }
func (m *RegisterUserReq) String() string { return proto.CompactTextString(m) }
func (*RegisterUserReq) ProtoMessage()    {}
func (*RegisterUserReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_de15a12e8d808d3f, []int{8}
}

func (m *RegisterUserReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RegisterUserReq.Unmarshal(m, b)
}
func (m *RegisterUserReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RegisterUserReq.Marshal(b, m, deterministic)
}
func (m *RegisterUserReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RegisterUserReq.Merge(m, src)
}
func (m *RegisterUserReq) XXX_Size() int {
	return xxx_messageInfo_RegisterUserReq.Size(m)
}
func (m *RegisterUserReq) XXX_DiscardUnknown() {
	xxx_messageInfo_RegisterUserReq.DiscardUnknown(m)
}

var xxx_messageInfo_RegisterUserReq proto.InternalMessageInfo

func (m *RegisterUserReq) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

func (m *RegisterUserReq) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

func (m *RegisterUserReq) GetNickName() string {
	if m != nil {
		return m.NickName
	}
	return ""
}

type RegisterUserRsp struct {
	Status               bool     `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	Msg                  string   `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RegisterUserRsp) Reset()         { *m = RegisterUserRsp{} }
func (m *RegisterUserRsp) String() string { return proto.CompactTextString(m) }
func (*RegisterUserRsp) ProtoMessage()    {}
func (*RegisterUserRsp) Descriptor() ([]byte, []int) {
	return fileDescriptor_de15a12e8d808d3f, []int{9}
}

func (m *RegisterUserRsp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RegisterUserRsp.Unmarshal(m, b)
}
func (m *RegisterUserRsp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RegisterUserRsp.Marshal(b, m, deterministic)
}
func (m *RegisterUserRsp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RegisterUserRsp.Merge(m, src)
}
func (m *RegisterUserRsp) XXX_Size() int {
	return xxx_messageInfo_RegisterUserRsp.Size(m)
}
func (m *RegisterUserRsp) XXX_DiscardUnknown() {
	xxx_messageInfo_RegisterUserRsp.DiscardUnknown(m)
}

var xxx_messageInfo_RegisterUserRsp proto.InternalMessageInfo

func (m *RegisterUserRsp) GetStatus() bool {
	if m != nil {
		return m.Status
	}
	return false
}

func (m *RegisterUserRsp) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

func init() {
	proto.RegisterType((*UserInfoReq)(nil), "admin_service.UserInfoReq")
	proto.RegisterType((*UserInfoRsp)(nil), "admin_service.UserInfoRsp")
	proto.RegisterType((*UserLoginReq)(nil), "admin_service.UserLoginReq")
	proto.RegisterType((*UserLoginRsp)(nil), "admin_service.UserLoginRsp")
	proto.RegisterType((*UserEditReq)(nil), "admin_service.UserEditReq")
	proto.RegisterType((*UserEditRsp)(nil), "admin_service.UserEditRsp")
	proto.RegisterType((*UploadProfileReq)(nil), "admin_service.UploadProfileReq")
	proto.RegisterType((*UploadProfileRsp)(nil), "admin_service.UploadProfileRsp")
	proto.RegisterType((*RegisterUserReq)(nil), "admin_service.RegisterUserReq")
	proto.RegisterType((*RegisterUserRsp)(nil), "admin_service.RegisterUserRsp")
}

func init() { proto.RegisterFile("tcp_service.proto", fileDescriptor_de15a12e8d808d3f) }

var fileDescriptor_de15a12e8d808d3f = []byte{
	// 393 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x54, 0x4f, 0x4b, 0xfb, 0x40,
	0x10, 0xa5, 0xbf, 0xfc, 0x28, 0xe9, 0x34, 0xd5, 0x3a, 0x07, 0x29, 0x11, 0xb4, 0x04, 0x14, 0x4f,
	0x15, 0xf4, 0xa0, 0xa0, 0xa7, 0x42, 0x05, 0x41, 0x62, 0x8d, 0xe4, 0xe2, 0x45, 0x62, 0xb2, 0x2d,
	0x8b, 0x69, 0xb3, 0xee, 0xa4, 0xf6, 0x0b, 0xe8, 0xf7, 0x96, 0xfc, 0x2b, 0xc9, 0x6a, 0x02, 0xf5,
	0xd4, 0xce, 0xcc, 0xdb, 0x79, 0x33, 0x6f, 0x66, 0x02, 0x7b, 0xb1, 0x2f, 0x5e, 0x88, 0xc9, 0x0f,
	0xee, 0xb3, 0x91, 0x90, 0x51, 0x1c, 0x61, 0xcf, 0x0b, 0x16, 0x7c, 0x59, 0x38, 0xad, 0x63, 0xe8,
	0xba, 0xc4, 0xe4, 0xdd, 0x72, 0x16, 0x39, 0xec, 0x1d, 0xf7, 0xa1, 0x9d, 0x9a, 0xc1, 0xa0, 0x35,
	0x6c, 0x9d, 0x76, 0x9c, 0xdc, 0xb2, 0x78, 0x09, 0x46, 0xa2, 0x0e, 0x86, 0x26, 0xe8, 0x36, 0xf7,
	0xdf, 0x6c, 0x6f, 0xc1, 0x06, 0xff, 0xd2, 0xc8, 0xc6, 0xc6, 0x13, 0xd8, 0x99, 0xca, 0x68, 0xc6,
	0x43, 0x36, 0xe5, 0x7e, 0xbc, 0x92, 0x6c, 0xa0, 0xa5, 0x08, 0xc5, 0x6b, 0x8d, 0xc1, 0x48, 0xb2,
	0xdd, 0x47, 0x73, 0xbe, 0x6c, 0x28, 0x29, 0xe1, 0x9a, 0x7a, 0x44, 0xeb, 0x48, 0x06, 0x05, 0x57,
	0x61, 0x5b, 0x57, 0xe5, 0x1c, 0x59, 0xbd, 0x14, 0x7b, 0xf1, 0x8a, 0xd2, 0x1c, 0xba, 0x93, 0x5b,
	0xd8, 0x07, 0x6d, 0x41, 0xf3, 0xfc, 0x79, 0xf2, 0xd7, 0xfa, 0x6a, 0x65, 0x9d, 0x4e, 0x02, 0x1e,
	0x37, 0xb1, 0x0f, 0xa1, 0x6b, 0xb3, 0xb5, 0x52, 0x40, 0xd9, 0x95, 0x20, 0x1e, 0xc2, 0x60, 0x83,
	0xc8, 0x9a, 0x2d, 0xbb, 0x2a, 0x6a, 0xfd, 0xaf, 0xaa, 0x65, 0x5d, 0x96, 0xca, 0xd8, 0xaa, 0x81,
	0x1b, 0xe8, 0xbb, 0x22, 0x8c, 0xbc, 0x20, 0x97, 0xb5, 0xa9, 0x89, 0x3e, 0x68, 0xae, 0x0c, 0x8b,
	0xd7, 0xae, 0x0c, 0x7f, 0xbe, 0xde, 0x8a, 0xdb, 0x83, 0x5d, 0x87, 0xcd, 0x39, 0xc5, 0x4c, 0x26,
	0x0c, 0x7f, 0x9c, 0x5e, 0x45, 0x17, 0x4d, 0xd1, 0xe5, 0x5a, 0xa1, 0xd8, 0xa6, 0xbe, 0xf3, 0x4f,
	0x0d, 0x8c, 0x74, 0xfd, 0x9f, 0xb2, 0xed, 0xc7, 0x31, 0xe8, 0xc5, 0x5a, 0xa3, 0x39, 0xaa, 0x5c,
	0xc6, 0xa8, 0x74, 0x16, 0x66, 0x6d, 0x8c, 0x04, 0xde, 0x82, 0x91, 0x4c, 0xa9, 0x31, 0x4f, 0xbe,
	0x4d, 0x66, 0x6d, 0x8c, 0x04, 0x3e, 0x42, 0xaf, 0x22, 0x3d, 0x1e, 0xa9, 0x60, 0x65, 0xac, 0x66,
	0x33, 0x80, 0x04, 0x4e, 0xa0, 0xb3, 0x39, 0x03, 0x3c, 0xf8, 0x85, 0xbb, 0x38, 0x32, 0xb3, 0x3e,
	0x48, 0x02, 0x6d, 0x30, 0xca, 0x9a, 0xe3, 0xa1, 0x02, 0x56, 0x66, 0x6e, 0x36, 0xc6, 0x49, 0x8c,
	0xf5, 0xe7, 0xf6, 0x59, 0xfa, 0x31, 0x7a, 0x6d, 0xa7, 0x3f, 0x17, 0xdf, 0x01, 0x00, 0x00, 0xff,
	0xff, 0xe6, 0xc3, 0xda, 0xf2, 0xa8, 0x04, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// AdminServiceClient is the client API for AdminService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type AdminServiceClient interface {
	UserInfo(ctx context.Context, in *UserInfoReq, opts ...grpc.CallOption) (*UserInfoRsp, error)
	EditUserInfo(ctx context.Context, in *UserEditReq, opts ...grpc.CallOption) (*UserEditRsp, error)
	UploadProfile(ctx context.Context, in *UploadProfileReq, opts ...grpc.CallOption) (*UploadProfileRsp, error)
	UserLogin(ctx context.Context, in *UserLoginReq, opts ...grpc.CallOption) (*UserLoginRsp, error)
	RegisterUser(ctx context.Context, in *RegisterUserReq, opts ...grpc.CallOption) (*RegisterUserRsp, error)
}

type adminServiceClient struct {
	cc *grpc.ClientConn
}

func NewAdminServiceClient(cc *grpc.ClientConn) AdminServiceClient {
	return &adminServiceClient{cc}
}

func (c *adminServiceClient) UserInfo(ctx context.Context, in *UserInfoReq, opts ...grpc.CallOption) (*UserInfoRsp, error) {
	out := new(UserInfoRsp)
	err := c.cc.Invoke(ctx, "/admin_service.adminService/UserInfo", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adminServiceClient) EditUserInfo(ctx context.Context, in *UserEditReq, opts ...grpc.CallOption) (*UserEditRsp, error) {
	out := new(UserEditRsp)
	err := c.cc.Invoke(ctx, "/admin_service.adminService/EditUserInfo", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adminServiceClient) UploadProfile(ctx context.Context, in *UploadProfileReq, opts ...grpc.CallOption) (*UploadProfileRsp, error) {
	out := new(UploadProfileRsp)
	err := c.cc.Invoke(ctx, "/admin_service.adminService/UploadProfile", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adminServiceClient) UserLogin(ctx context.Context, in *UserLoginReq, opts ...grpc.CallOption) (*UserLoginRsp, error) {
	out := new(UserLoginRsp)
	err := c.cc.Invoke(ctx, "/admin_service.adminService/UserLogin", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adminServiceClient) RegisterUser(ctx context.Context, in *RegisterUserReq, opts ...grpc.CallOption) (*RegisterUserRsp, error) {
	out := new(RegisterUserRsp)
	err := c.cc.Invoke(ctx, "/admin_service.adminService/RegisterUser", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AdminServiceServer is the server API for AdminService service.
type AdminServiceServer interface {
	UserInfo(context.Context, *UserInfoReq) (*UserInfoRsp, error)
	EditUserInfo(context.Context, *UserEditReq) (*UserEditRsp, error)
	UploadProfile(context.Context, *UploadProfileReq) (*UploadProfileRsp, error)
	UserLogin(context.Context, *UserLoginReq) (*UserLoginRsp, error)
	RegisterUser(context.Context, *RegisterUserReq) (*RegisterUserRsp, error)
}

// UnimplementedAdminServiceServer can be embedded to have forward compatible implementations.
type UnimplementedAdminServiceServer struct {
}

func (*UnimplementedAdminServiceServer) UserInfo(ctx context.Context, req *UserInfoReq) (*UserInfoRsp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UserInfo not implemented")
}
func (*UnimplementedAdminServiceServer) EditUserInfo(ctx context.Context, req *UserEditReq) (*UserEditRsp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method EditUserInfo not implemented")
}
func (*UnimplementedAdminServiceServer) UploadProfile(ctx context.Context, req *UploadProfileReq) (*UploadProfileRsp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UploadProfile not implemented")
}
func (*UnimplementedAdminServiceServer) UserLogin(ctx context.Context, req *UserLoginReq) (*UserLoginRsp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UserLogin not implemented")
}
func (*UnimplementedAdminServiceServer) RegisterUser(ctx context.Context, req *RegisterUserReq) (*RegisterUserRsp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RegisterUser not implemented")
}

func RegisterAdminServiceServer(s *grpc.Server, srv AdminServiceServer) {
	s.RegisterService(&_AdminService_serviceDesc, srv)
}

func _AdminService_UserInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserInfoReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminServiceServer).UserInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/admin_service.adminService/UserInfo",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminServiceServer).UserInfo(ctx, req.(*UserInfoReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _AdminService_EditUserInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserEditReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminServiceServer).EditUserInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/admin_service.adminService/EditUserInfo",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminServiceServer).EditUserInfo(ctx, req.(*UserEditReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _AdminService_UploadProfile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UploadProfileReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminServiceServer).UploadProfile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/admin_service.adminService/UploadProfile",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminServiceServer).UploadProfile(ctx, req.(*UploadProfileReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _AdminService_UserLogin_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserLoginReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminServiceServer).UserLogin(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/admin_service.adminService/UserLogin",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminServiceServer).UserLogin(ctx, req.(*UserLoginReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _AdminService_RegisterUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegisterUserReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminServiceServer).RegisterUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/admin_service.adminService/RegisterUser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminServiceServer).RegisterUser(ctx, req.(*RegisterUserReq))
	}
	return interceptor(ctx, in, info, handler)
}

var _AdminService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "admin_service.adminService",
	HandlerType: (*AdminServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "UserInfo",
			Handler:    _AdminService_UserInfo_Handler,
		},
		{
			MethodName: "EditUserInfo",
			Handler:    _AdminService_EditUserInfo_Handler,
		},
		{
			MethodName: "UploadProfile",
			Handler:    _AdminService_UploadProfile_Handler,
		},
		{
			MethodName: "UserLogin",
			Handler:    _AdminService_UserLogin_Handler,
		},
		{
			MethodName: "RegisterUser",
			Handler:    _AdminService_RegisterUser_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "tcp_service.proto",
}
